Repository ConnectAI-E/Dingtalk-OpenAI, pull requests merged in 2023-06, with the labels that each got.

#238 doc: 添加stream模式的配置步骤
  README.md
Labels: documentation

#242 chore: ⬆️ dingtalk-stream-sdk-go 依赖版本升级
  go.mod
  go.sum
  main.go
  public/example_bot.go
  public/example_event.go
Labels: feature

#245 doc: 调整密钥的配置说明信息
  README.md
  config.example.yml
Labels: documentation

#247 如果上下文超过最大Token，删除最早的对话，而不是直接报错重置。并且将上下文最大长度参数作为变量引出。
  README.md
  config.example.yml
  config/config.go
  docker-compose.yml
  pkg/chatgpt/chatgpt.go
  pkg/chatgpt/context.go
Labels: feature

#249 feat: 同步OpenAI更新，更新0613模型及3.5 16K模型 及 修复stream模式引入的两个bug
  README.md
  config.example.yml
  config/config.go
  docker-compose.yml
  go.mod
  go.sum
  main.go
  pkg/chatgpt/chatgpt.go
  pkg/chatgpt/context.go
  prompt.yml
  public/public.go
Labels: feature

#258 feat: 同时将镜像推送到国内阿里仓库,解决镜像下载问题
  .github/workflows/docker-image.yml
Labels: feature

#261 doc: 说明文档中更改镜像为阿里仓库,解决拉取镜像难的问题
  .github/workflows/docker-image.yml
  README.md
  docker-compose.yml
Labels: documentation

#263 fix: 解决使用docker运行获取秘钥异常的问题
  config/config.go
Labels: bug
