Repository ConnectAI-E/Dingtalk-OpenAI, pull requests merged in 2023-04, with the labels that each got.

#150 feat: change config type json to yml
  .github/workflows/go-binary-release.yml
  .gitignore
  Dockerfile
  README.md
  config.dev.json
  config.example.yml
  config/config.go
  docker-compose.yml
Labels: feature

#151 perf: content TrimSpace
  main.go
  public/public.go
Labels: feature

#152 fix: 兼容当 SenderStaffId 字段为空的场景
  pkg/dingbot/dingbot.go
  pkg/process/process_request.go
  public/public.go
Labels: bug

#154 feat: 支持聊天模式限制能力
  README.md
  config.example.yml
  config/config.go
  docker-compose.yml
  main.go
Labels: feature

#158 feat: 支持聊天记录存入以及查询的能力
  .gitignore
  README.md
  docker-compose.yml
  go.mod
  go.sum
  main.go
  pkg/cache/user_base.go
  pkg/cache/user_chatid.go
  pkg/chatgpt/context.go
  pkg/db/chat.go
  pkg/db/sqlite.go
  pkg/dingbot/dingbot.go
  pkg/process/process_request.go
  public/public.go
  public/tools.go
Labels: feature

#159 feat: 支持自定义分组以及用户白名单的能力支持定义系统管理员的能力
  README.md
  config.example.yml
  config/config.go
  docker-compose.yml
  main.go
  pkg/db/chat.go
  pkg/process/process_request.go
  public/tools.go
Labels: feature

#160 fix: 信息查询时的错漏
  pkg/db/chat.go
Labels: bug

#162 fix: 初始化时没有data目录的问题,暂时注释余额功能及其他修复
  pkg/db/sqlite.go
  pkg/process/process_request.go
  public/public.go
  public/tools.go
Labels: bug

#163 fix: 将示例配置的配置信息调整为空
  config.example.yml
Labels: bug

#166 fix: 解决请求信息通过伪造绕过校验的问题
  pkg/db/chat.go
  pkg/process/process_request.go
Labels: bug

#168 fix: 修复配置指向的错误
  config/config.go
Labels: bug

#170 feat: 增加域名以及证书信息的查询能力
  main.go
  pkg/ops/opstools.go
  pkg/process/db.go
  pkg/process/image.go
  pkg/process/opstools.go
  pkg/process/process_request.go
  public/tools.go
Labels: feature

#171 feat: 添加对回调请求校验的能力,解决可被其他人调用的安全隐患
  README.md
  config.example.yml
  config/config.go
  docker-compose.yml
  main.go
  pkg/logger/logger.go
  pkg/process/process_request.go
  public/chat.go
  public/public.go
  public/tools.go
Labels: feature

#172 feat: 支持help自定义,将用户指南单独成文，便于整合以及内容呈现
  README.md
  config.example.yml
  config/config.go
  docker-compose.yml
  docs/userGuide.md
  main.go
  prompt.yml
Labels: feature

#173 perf: 优化添加secret的逻辑,支持配置多个
  README.md
  config.example.yml
  config/config.go
  docker-compose.yml
  public/tools.go
Labels: feature

#175 perf: 将管理员校验的字段改为userid,从而解决普通用户绕过校验的问题
  README.md
  config.example.yml
  docker-compose.yml
  main.go
  pkg/process/db.go
  public/tools.go
Labels: feature

#174 feat: 添加默认路径的GET路由并提醒用户服务器状态
  main.go
Labels: feature

#177 perf: 新增outgoing类型机器人下使用的放通逻辑
  public/tools.go
Labels: bug

#179 perf: 优化一些回复信息及信息记录，移除不再使用的欢迎代码
  pkg/process/db.go
  pkg/process/process_request.go
  public/public.go
Labels: documentation

#183 fix: 修复chatgpt.go中处理AzureOn相关逻辑时重新定义变量config导致程序崩溃的问题
  pkg/chatgpt/chatgpt.go
  prompt.yml
Labels: bug

#185 fix: 修复余额查询的接口
  docs/userGuide.md
  pkg/process/process_request.go
  public/balance.go
  public/public.go
Labels: bug

#190 feat: 新增黑名单用户及VIP用户处理逻辑，同时修改ALLOW_USERS的校验为userid（SenderStaffId），将用户相关校验统一为userid
  README.md
  config.example.yml
  config/config.go
  docker-compose.yml
  main.go
  pkg/process/process_request.go
  prompt.yml
  public/tools.go
Labels: feature

#192 fix: 更新用户请求次数缓存失效时间为第二天零点，修复max_request配置达不到预期的问题
  pkg/cache/user_requese.go
Labels: bug

#194 docs: 修复一些GPT的拼写错误
  config/config.go
  pkg/cache/user_chatid.go
  pkg/cache/user_context.go
Labels: documentation

#195 fix: 修复docker镜像名称的取值问题
  .github/workflows/docker-image.yml
  README.md
Labels: bug

#205 perf: 用户提问含有敏感词，新增相关日志输出（userid及用户提问内容）
  main.go
Labels: feature

#209 feat: 将回复消息格式修改为Markdown，支持代码块的展示（仅PC端支持），如返回消息是Markdown格式将直接渲染
  pkg/process/process_request.go
Labels: feature

#211 feat: 将web框架改成gin框架
  go.mod
  go.sum
  main.go
Labels: feature

#212 fix: request time out
  pkg/chatgpt/chatgpt.go
Labels: bug

#217 fix: 将docker-compose的outgoing配置留空
  docker-compose.yml
Labels: bug

#220 fix: 修复敏感词的替换显示问题（由于钉钉回复的消息格式已改为markdown格式，原替换为*的逻辑会有语法冲突）
  README.md
  config.example.yml
  config/config.go
  docker-compose.yml
  public/tools.go
Labels: bug
