Repository ConnectAI-E/Dingtalk-OpenAI, pull requests merged in 2023-03, with the labels that each got.

#58 feat: 升级模型为gpt-3.5
  .github/release-drafter.yml
  .github/workflows/docker-image.yml
  .github/workflows/go-binary-release.yml
  .github/workflows/release.yml
  go.mod
  go.sum
  pkg/chatgpt/context.go
Labels: feature

#60 feat: 优化与钉钉机器人交互相关的一些细节
  main.go
  public/dingtalk.go
Labels: feature

#66 feat: 将上下文改成cache方式保留
  .pre-commit-config.yaml
  Dockerfile
  README.md
  config.dev.json
  config/config.go
  go.mod
  go.sum
  main.go
  pkg/chatgpt/chatgpt.go
  pkg/chatgpt/chatgpt_test.go
  pkg/chatgpt/context.go
  pkg/chatgpt/context_test.go
  public/gpt.go
  public/public.go
  service/user.go
Labels: feature

#67 feat: 支持配置proxy的能力
  README.md
  config.dev.json
  config/config.go
  main.go
  pkg/chatgpt/chatgpt.go
  pkg/chatgpt/chatgpt_test.go
  pkg/chatgpt/context_test.go
Labels: feature

#68 feat: 添加查询余额的交互能力
  README.md
  go.mod
  go.sum
  main.go
  public/gpt.go
Labels: feature

#76 doc: 调整容器部署的方式
  README.md
Labels: documentation

#75 feat: 添加 docker compose 部署方式
  README.md
  docker-compose.yml
Labels: feature

#93 feat: 支持gpt4.0的自定义
  README.md
  go.mod
  go.sum
  pkg/chatgpt/chatgpt.go
  pkg/chatgpt/context.go
Labels: feature

#94 feat: 支持请求失败之后自动重试的能力
  go.mod
  go.sum
  main.go
  public/gpt.go
Labels: feature

#96 feat: add docker push to ghcr
  .github/workflows/docker-image.yml
Labels: feature

#98 feat: add user request limit config
  README.md
  config.dev.json
  config/config.go
  docker-compose.yml
  go.mod
  main.go
  pkg/cache/user_base.go
  pkg/cache/user_context.go
  pkg/cache/user_mode.go
  pkg/cache/user_requese.go
  pkg/chatgpt/export.go
  pkg/process/process_request.go
  public/public.go
  service/user.go
Labels: feature

#99 feat: 添加prompt的集成
  main.go
  pkg/chatgpt/context.go
  pkg/process/process_request.go
  pkg/process/prompt.go
Labels: feature

#100 fix: 修复在群聊中无法使用prompt的问题
  main.go
Labels: bug

#106 feat: 支持prompt通过配置文件自定义
  README.md
  config/prompt.go
  go.mod
  go.sum
  pkg/process/process_request.go
  pkg/process/prompt.go
  prompt.yml
  public/public.go
Labels: feature

#107 fix: 将prompt.yml 文件打到二进制以及docker镜像中
  .github/workflows/go-binary-release.yml
  Dockerfile
Labels: bug

#115 feat: 增加了生成图片的能力,以及其他一系列优化
  .github/workflows/TOC.yml
  README.md
  config.dev.json
  config/config.go
  docker-compose.yml
  go.mod
  go.sum
  main.go
  pkg/chatgpt/context.go
  pkg/chatgpt/export.go
  pkg/process/process_request.go
  public/dingtalk.go
  public/public.go
Labels: feature

#128 feat: 优化钉钉机器人的消息发送方式,兼容outgoing模式
  README.md
  main.go
  pkg/process/process_request.go
  public/dingtalk.go
  public/public.go
Labels: feature

#131 feat: 添加生成Linux命令的prompt
  prompt.yml
Labels: feature

#132 feat: 调整log库以及其他包的组织目录
  README.md
  config/config.go
  go.mod
  go.sum
  main.go
  pkg/chatgpt/export.go
  pkg/dingbot/dingbot.go
  pkg/logger/logger.go
  pkg/process/process_request.go
  public/balance.go
  public/logger/logger.go
  public/public.go
Labels: feature

#139 添加贡献者action
  .github/workflows/reademe-contributors.yml
  README.md
  main.go
Labels: feature

#141 refactor: `prompt.content + ?` => `prompt.prefix + ? + prompt.suffix`
  config/prompt.go
  pkg/process/prompt.go
  prompt.yml
Labels: feature

#144 feat: 支持gpt-4并解决退出不掉的问题
  README.md
  go.mod
  go.sum
  main.go
  public/public.go
Labels: feature
